const referral = require("express").Router();
const nodemailer = require("nodemailer");
const authVerify = require("../middlewares/authVerify");
require("dotenv").config();

referral.post('/', async (req, res, next) => {
	let linkToSend = req.body.link;
	let emailToSend = req.body.email;

	// Send the email
	let transporter = nodemailer.createTransport({
		host: "smtp.mailtrap.io",
		port: 2525,
		auth: {
			user: process.env.MAILTRAP_ID, //generated by Mailtrap
			pass: process.env.MAILTRAP_PWD, //generated by Mailtrap
		}
	});
	let mailOptions = {
		from: `"CryptoX" <${process.env.COMPANY_MAIL}>`,
		to: emailToSend,
		subject: "Invitation to Register | CryptoX",
		text:
			"Hello there,\n\n" +
			"Register at CryptoX by clicking the below link and get Rs. 100 as bonus cash.\nLink: " +
			linkToSend +
			"\n\n\nRegards,\nCryptoX\n\nKeep Minting! :)",
	};

	let info;
	try {
		info = await transporter.sendMail(mailOptions);
	} catch (err) {
		console.log(err);
		return next(new Error("Unable to send Email Verification mail."));
	}

	res.status(200).json({
		message: "Invite Sent!",
		mailinfo: info.messageId
	});
});

referral.use(authVerify);

referral.get('/', (req, res, next) => {

});

module.exports = referral;