const nodemailer = require("nodemailer");
require("dotenv").config();

const User = require("../models/user");

const invite = async (req, res, next) => {
	console.log(req.body);
	const { inviteLink, emailToSend } = req.body;

	// Send the email
	let transporter = nodemailer.createTransport({
		host: "smtp.mailtrap.io",
		port: 2525,
		auth: {
			user: process.env.MAILTRAP_ID, //generated by Mailtrap
			pass: process.env.MAILTRAP_PWD, //generated by Mailtrap
		},
	});
	console.log(inviteLink);
	let mailOptions = {
		from: `"CryptoX" <${process.env.COMPANY_MAIL}>`,
		to: emailToSend,
		subject: "Invitation to Register | CryptoX",
		text:
			"Hello there,\n\n" +
			"Register at CryptoX by clicking the below link and get Rs. 100 as bonus cash.\nLink: " +
			inviteLink +
			"\n\n\nRegards,\nCryptoX\n\nKeep Minting! :)",
	};

	let info;
	try {
		info = await transporter.sendMail(mailOptions);
	} catch (err) {
		console.log(err);
		return next(new Error("ERR: Unable to send Email Verification mail."));
	}

	res.status(200).json({
		message: "Invite Sent!",
		mailinfo: info.messageId,
	});
};

module.exports.invite = invite;
